### ISSUE TITLE
Usage as git hook?

### ISSUE THREAD

**Issue by zachlysobey** [antham/gommit#1]
Do you have any suggestions for using this to (automatically) enforce good commit messages for a project? Like a post-commit or pre-push hook (if those are things).

It wasn't immediately clear if this was possible, but if so, it would be (even more) hugely useful.

I work on a project at work that receives commits from people on other teams, who tend to ignore our contributing docs, so it would be great to force them into submission ;-)

Thanks for your great work!

**Comment by antham** [comment]
Yep I'm working on that to have it both in CI and as git hook, so it will be possible to scan locally commit from a git hook and ensuring remotely on a CI that a branch fit conventions. I tried on circle but I'm facing some issues I'm solving currently, I will put a complete example on README once it will be fine.

**Comment by antham** [comment]
@zachlysobey This issue is solved, everything is detailled in README.
