### ISSUE TITLE
gommit checks commits outside of specified range

### ISSUE THREAD

**Issue by nrdmn** [antham/gommit#12]
Hi,
gommit seems to check commit outside of the specified range. I've got a test repository at https://github.com/nrdmn/gommit-test. When I run `gommit check range HEAD~1 HEAD`, gommit complains about commits that are older than HEAD~1. I'm using version 2.1.1.

Commits:
```
$ git log --oneline --graph --pretty=tformat:"%H %s"
*   7d459fec7b2bdeed49235afa4351bffee3ed56ee Merge branch 'b'
|\  
| * 8d953429d21a0e8bcc211a671c862c81dd7053bc xyz add quux
* | 32e57995fb430bc71bfe2f72a6cf28f16b5bf12b xyz add baz
|/  
*   c019554ea4190f4e353b65ed5b7b91cb69d08560 Merge branch 'a'
|\  
| * bc29183dc55a976cd60142a005d8fd0b1e4316c9 xyz add bar
* | f9e9bc63c88ff7f2154eb91becf5e0649b3c668d xyz add foo
|/  
* 4e4da5034b797b3369851ef100d1833b6e441f49 add readme
* 95b78126faa5f115624d0595067666956eabbc4d initial commit
```
Config:
```
[config]
exclude-merge-commits=true
check-summary-length=true
summary-length=50

[matchers]
all="xyz"

[examples]
a_simple_commit="""
x A commit message
"""
an_extended_commit="""
x A commit message

* first line
* second line
* and so on...
"""
```
Output:
```
$ gommit check range HEAD~1 HEAD
commit 7d459fec7b2bdeed49235afa4351bffee3ed56ee
Author: Nick Erdmann <n@nirf.de>
Date:   Sat Apr 14 01:37:50 2018 +0200

    Merge branch 'b'


commit 32e57995fb430bc71bfe2f72a6cf28f16b5bf12b
Author: Nick Erdmann <n@nirf.de>
Date:   Sat Apr 14 01:36:50 2018 +0200

    xyz add baz


----

Id       : 4e4da5034b797b3369851ef100d1833b6e441f49
Message  : 
           add readme
           

Error(s) : - No template match commit message

=======

Your message must match one of those following patterns :

----

An extended commit : 

x A commit message

* first line
* second line
* and so on...

----

A simple commit : 

x A commit message
```

**Comment by antham** [comment]
Hi and thanks for your detailed reporting.

It was not intended to browse a complex graph only a single branch, so this issue is due to the first simple implementation to fit that requirement. Fortunately, I wrote on other apps a version able to parse git DAG, so I backported it here. Please try the brand new version and let me know if it's ok for you, I tried already and everything was working as expected.

**Comment by nrdmn** [comment]
Thanks, this issue seems to be fixed!
Unfortunately gommit can't find commits by their IDs anymore. Using the repository mentioned above:
```
$ gommit check range c019554ea4190f4e353b65ed5b7b91cb69d08560 HEAD
Reference "c019554ea4190f4e353b65ed5b7b91cb69d08560" can't be found in git repository
```

**Comment by antham** [comment]
Yeah I noticed, yesterday night this trouble, it's due to an issue in gogit library to resolve a revision which is a sha, I have opened a PR there but did not finished the implementation. I did a workaround in this PR    #13, I will merge it later, I have no time now.

**Comment by antham** [comment]
So finally I had the time to produce a release, please try the version 2.1.3 and check if it's ok for you.

**Comment by nrdmn** [comment]
Perfect, thanks a lot!
