### ISSUE TITLE
[Idea] - Remote gommit config

### ISSUE THREAD

**Issue by NikitaCOEUR** [antham/gommit#161]
I started deploying gommit on various projects within my organization to verify commit messages from different users using pre-commit (via lefthook).
And I think it would be useful to be able to define a remote configuration file to centralize the common configuration across different repositories.
Commit messages need to be standardized across multiple repos, but there may arise a new need that requires a modification of the .gommit.toml file. 
- Having to go back to all the repos can be truly burdensome.

Is it feasible to add a feature to specify a gommit.toml file from a remote repo (with the bonus of specifying the reference...)? The idea would be to:
- When running gommit,
- check the local gommit.toml file, if a remote section is present : retrieve the remote file from the local .git (for caching purposes), then execute the binary based on the retrieved configuration.

What do you think about this?

**Comment by antham** [comment]
Hello,
thanks for the suggestion.
What about a gist? A git repository seems a bit too much in my opinion.

**Comment by NikitaCOEUR** [comment]
A gist seems to be a quick win yes. 😀

**Comment by antham** [comment]
I was thinking to this idea and how to implement it, but I'm unable to wrap my head around. It seems really complicated when I try to think about the details for instance the fetching/caching/cache invalidation topic, I can't define a good implementation.

I'm not sure about the use case also, it seems to me once you defined a config, it won't change that much in most of the case, it's something pretty static.

While the idea is interesting it seems the cost of the implementation vs the real usage are not balanced, so I'm going to close the ticket, sorry 😕 , but thank you for the suggestion which is good 👍.
