### ISSUE TITLE
Publish as a npm package?

### ISSUE THREAD

**Issue by zachlysobey** [antham/gommit#4]
This seems to be the final item preventing me from using this (easily) in production.

If you could add it, I would be ever-so grateful.

**Comment by antham** [comment]
A npm package, what do you mean ?

**Comment by zachlysobey** [comment]
Pretty much, I'd just like to be able to use this in my javascript projects using npm.

I.e. `npm install gommit --save-dev` to install this project as a dependency.

Given that this itself is *not* a JS project, you'd probably have to write a wrapper, perhaps using something like: https://github.com/kevva/bin-wrapper

Honestly, this isn't something I've really done before, and I'm not really even 100% its appropriate for your project.

If you wanted to take a stab at it, that would be amazing. If not, maybe I can take a shot at writing the JS wrapper at some point in the coming weeks?

**Comment by antham** [comment]
I saw dev package.json part only like things related to js, I would put a command like that rather in script part, but I get the idea. If you want to give it a try why not.

**Comment by dschnare** [comment]
@zachlysobey @antham Hey guys, I too would like this tool wrapped in a NPM module. So I wrote one. @zachlysobey hope you didn't get too far in your implementation, but I needed a solution. You can check out the project here: https://github.com/dschnare/gommitjs

**Comment by zachlysobey** [comment]
@dschnare nope, its just been a line on a TODO list. Awesome job putting that together. I'll give it a test-drive soon.

**Comment by antham** [comment]
@dschnare thanks for your geat job, I added your library to gommit README : https://github.com/antham/gommit#third-part-libraries

I can close this issue now.

:+1:
